### PR TITLE
Allow specifying facingMode for camera

### PR DESCRIPTION
**Pull request by legoscia**
I'd like to scan QR codes using the user-facing camera.  This change
adds an optional argument to the constructor specifying the default
facingMode to try.

### CODE REVIEW

**Comment by cscwilson** [comment]
Hi Sir , i  have try your changed file but it seem the camera still using the back camera instead of facing camera. could you help?

**Comment by legoscia** [comment]
@cscwilson You'd need to specify facing mode "user", like this:

    const qrScanner = new QrScanner(videoElem, result => console.log('decoded qr code:', result), 'user');

**Comment by cscwilson** [comment]
@legoscia i am using their demo to edit, am i change the line on index.html like below:

  QrScanner.hasCamera().then(hasCamera => camHasCamera.textContent = hasCamera);

    const scanner = new QrScanner(video, result => setResult(camQrResult, result),'user'); //i add 'user' here!  
    scanner.start();

am i right? but i tested it still using back cam....

**Comment by legoscia** [comment]
@cscwilson That's strange, I would expect that to work. It's worth noting that the facing mode is just a preference; if it can't get the specified camera, it falls back to any camera it can get. Not sure what might stop it from getting the front camera, though...

**Comment by cscwilson** [comment]
i find it have changed 4 files qr-scanner.min.js,qr-scanner.min.js.map, src/qr-scanner.js,types/qr-scanner.d.ts. if i am base on your demo page to edit . am i change this 4 files and i can get the font camera image ?

**Comment by legoscia** [comment]
Yes, that should be enough. Perhaps check if the old versions have been cached in the browser?

**Comment by cscwilson** [comment]
do you mind i zip my files to you for check?

**Comment by cscwilson** [comment]
@legoscia if you don't mind , please help to take a look if you can , below is the download link which i have zip it .

https://gofile.io/?c=f8xJzG

Thanks!

Wilson

**Comment by Errorname** [comment]
Ping @danimoh, in case this PR flew under the radar 🙂

**Comment by piotrblasiak** [comment]
How about making it possible to select any camera? What if there are several cameras connected?

**Pull request merged**
